server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Jackson Configuration
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false

  # Spring MVC Configuration
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # Kafka Configuration
  kafka:
    consumer:
      bootstrap-servers: host.docker.internal:9092
      group-id: stock-data
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: host.docker.internal:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/finKollector
    username: root
    password: 1234

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      password: 1234

# Email Configuration
  mail:
    host: smtp.gmail.com
    port: 465
    username: xivpark1110@gmail.com
    password: cbpzbxqraippnelg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          port: 465
          timeout: 5000


# Logging Configuration
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

# Email Code Expiration-time Configurations
email:
  code:
    expiration-time: 10
